# Site
repository: vuduclong0309/vuduclong0309.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vu Duc Long
title: Ex Data Engineer, Master Student (Data Science and Financial Engineer)
email: vuduclong0309@gmail.com
website: https://vuduclong0309.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  vuduclong0309
stackoverflow_username: "6908781"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: vuduclong0309
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-file
  url: https://drive.google.com/file/d/1HJEP4yzZhP3gdpkSryXEKCr_YVyhhkLD/view?usp=share_link
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there! You can call me Long for short. I’m a currently a master student in Perth, Australia, focused in financial engineering and data science, with the 3-year working experience as a data engineer in Shopee Singapore.

  Beside the current interests, having built a game available on Google Play, this website, and an IEEE journal inspired from my bachelor thesis, I can say I'm an explorer.

  At the moment I'm most in touch with <mark>Python</mark> and <mark>Apache Spark</mark>.

  However, the aspect that's I'm most proud of is my resourcefulness and adaptability.

  "He who stops being better stops being good." - Oliver Cromwell


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: LongNShort
        link: https://longnshort.atlassian.net
        # link_text: Project Website
        sub_title: Data Engineer, Software Engineer, Data Analyst
        caption: August 2022 - Present
        additional_links:
          - title:  vuduclong0309/LongAndShort
            icon: fab fa-github
            url: https://github.com/vuduclong0309/LongAndShort
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A bridge that connects a software engineer and a traditional trader in taming the market ... or getting horribly bullied by it.
        description: | # this will include new lines to allow paragraphs
          My soul personal project of 2022. So far I have built an automated technical trading system; and an options trade semi-bot to follow with trade signal on Github. To request for a demo of my issue ticket & confluence, please contact me.

          I could always see a rift when it comes to high frequency trading for most ordinary people:
            - A software engineer often face problems with understanding financial terms.
            - A traditional retail trader finds building a high quality trading system a formidable task.

          LongNShort aim to eliminate the obstacle: A quality customizable automated trading system with the folling targets in consideration:
            - Well-documented market archive knowledge for an engineer
            - Easy-to-use for a trader, as much as using a script copied from a Youtube channel.

          Made possible with:
            - Tech Stack and Framework: <mark>Python, InteractiveBroker TWS API and Backtrader</mark>
            - Development tracking and knowledge archive: <mark>Atlassian JIRA and Confluence</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shopee Singapore - SEA Limited
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: July 2019 - August 2022
        quote: >
          - "I hope I didn't delete any user or item table by accident"
        description: | # this will include new lines to allow paragraphs
          Job duties:
            - Maintainer of Shopee 3PL Rebate logic, shop's chat response rate and provides
            data for Shopee Campaign Infographic (2019)
            - Maintainer of User Profile and Item Profile legacy database (2020-2021)
            - Design and Implement a Data Warehouse to capture Shopee chatbot metrics (2021)
            - Expand User Tagging Project - user level tags for newer regions (2022)
          Tech Stack / Framework: <mark>Python 2/3, Scala, Apache Spark 2.3-3.1, Apache Hadoop, Apache Airflow, Apache Superset, Apache Hive</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Western University of Australia
        caption: 2023 - Present
        sub_title: Master of Data Science
        quote: >
          - "Because I like Perth :D"

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: WorldQuant University
        caption: 2020 - Present
        sub_title: Master of Financial Engineer
        quote: >
          - "Hey perhaps I want to become a Quant" - Me, 2020, before knowing about derivation pricing. No regrets.
        description: | # this will include new lines to allow paragraphs
          Cumulative Grade Point Average: 90/100

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nanyang Techlogical University
        caption: 2015 - 2019
        sub_title: BSc Computer Science
        quote: >
          - Established in 1991, NTU is the second oldest autonomous university in the country and is considered as one of the most prestigious universities in the world by various international metrics. It is usually ranked amongst the world's top 20 institutions of higher learning (Wikipedia)

        description: | # this will include new lines to allow paragraphs
          Cumulative Grade Point Average: 4.60 - CONTINUED NEXT PAGE -
          TRANSCRIPT GUIDE PRINTED ON REVERSE           COMPLETED THE DEGREE OF BACHELOR OF ENGINEERING (COMPUTER SCIENCE), HONOURS (HIGHEST DISTINCTION) WITH AN ELECTIVE FOCUS AN ARTIFICIAL INTELLIGENCE AND AN ELECTIVE FOCUS IN DATA SCIENCE AND ANALYTICS

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Normally I'm very lazy (Well, on the positive side they say lazy people often find easy way to solve stuff)
        - For instance, most of the job / experience description above I probably just copy pasted from my documents (You can ask me for official document that I have copied for validation). I don't want to edit it since I blame it for potential Git merge conflict. (Sorry for that NTU section, by the way ^^)
        - I also "borrowed" this website template from a guy called Brett Harris
        - Nonetheless, I can be bribed with fruit juice and food. I believe my productivity is highest when I'm near a pantry.

      Some of my other interests and hobbies are:
      - Video Game (Welp, certainly not about creating game, one of my nightmare is designing game assets)
      - Manga (I'm NOT an Otaku)
        - I also "borrowed" a OCR translator (Japanese -> English) for reading raw manga in Japanese from leminhyen: <mark>https://github.com/vuduclong0309/Sugoi-Japanese-Translator</mark>
      - Ping Pong (I'm not Chinese btw, I'm Vietnamese)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
